### ISSUE TITLE
"Unable to infer the Laplace transform"

### ISSUE THREAD

**Issue by ab08028** [weissmanlab/magic#1]
Hi there,
First off, thanks for such a cool method and easy to follow documentation!

I am trying to run Magic on a single individual, using whole genome data (mean coverage ~55x, using the largest scaffolds that make up ~2Gb of a 2.4Gb genome). The species in question has been bottlenecked fairly recently, so there is a very low SNP rate. 

I ran combo_prep on my filtered vcf files, then windower first using the default baselength of 80, then I also tried 10 (hoping to get more info from the smaller scaffolds) and the default tbl stat.

When I run magic.py I get the following error no matter the baselength window size:

**"Unable to infer the Laplace transform. If you don't have any more data, you might want to try increasing the allowed extrapolation."**

I tried raising the extrapolation parameter to 1, and got the same error.

I'd love your advice about what might be going on here -- it may just be that I have too few SNPs to have any power with MAGIC. I was able to run MSMC (PSMC') on these same data, so was hoping to be able to make a comparison :)

Thanks so much for your help!

~Annabel 
Ph.D. Candidate
Wayne Lab, Lohmueller Lab
Ecology & Evolutionary Biology
UCLA

**Comment by weissman** [comment]
Hi Annabel,

Thank you for trying it out! This is probably a bug on my end. Quick check
-- you're using the latest version (downloaded after Aug 26th), right?

Do you have the *_counts.txt files put out by windower.py? If I can take a
look at those, I can probably figure out what's going on. But just in case,
do you you know the scaffold length distribution?

Thanks!
Daniel

**Comment by ab08028** [comment]
Hi Daniel,
Thanks so much for such a quick follow up! I really appreciate it :)

I just downloaded MAGIC yesterday so it should be the freshest version. 

Is there an email that’s best for me to send the _counts files to?

Thanks so much for your advice!

Best,
Annabel

**Comment by weissman** [comment]
Oh sorry, dbweissman@gmail.com is good. If it's easier, you can also share
them with me on Dropbox using that address.

On Fri, Oct 20, 2017 at 11:06 PM, Annabel Beichman <notifications@github.com
