### ISSUE TITLE
Input from simulations

### ISSUE THREAD

**Issue by arundurvasula** [weissmanlab/magic#2]
Hi Daniel,

I'm trying to use MAGIC on simulated data from msprime, but I'm not sure how I should input the data. Is the easiest way to directly write out an MSMC-style SNP file and a bed mask that includes the whole simulated region? Or should I output a VCF and go from there?

Thanks!
Arun

**Comment by weissman** [comment]
Hi Arun,

I see that I forgot to document this part. The ms2msmc.py script converts
ms-style output to MSMC input format. Then you can either make a fake
coverage file (just a whole bunch of lines of "80", or whatever your
minimum window size is) and use windower.py, or use this attached script
window_msN.py instead. window_msN.py is just if you want the distribution
of pairwise distances in your simulated sample, so you'd have to tweak it
if you're looking at a different tree property.

I hope that helps. I'm traveling right now, but I can get back to you with
more specifics when I get a chance if it would be helpful.

Best,
Daniel

**Comment by arundurvasula** [comment]
Thanks Daniel! I ended up writing a little function to do this in python since I'm using msprime to simulate sequence data. I have some questions about the output as well, but I will open another issue to keep things organized.

**Comment by arredondos** [comment]
Hello Daniel and Arun,

I came across this thread also looking for a way to run MAGIC on ms-simulated data, because the documentation on this is indeed lacking. Where can I find this window_msN.py script that generates the coverage files?

Thanks a lot,
Armando.

**Comment by weissman** [comment]
Hi Armando,
I just uploaded it to the repository. I still need to document everything though.
Best,
Daniel

**Comment by arredondos** [comment]
Thanks Daniel, that is very helpful.
